Repository plone/Products.CMFPlone, pull requests merged in 2018-05, with the labels that each got.

#2400 Move forgotten 'registered' template from skins to plone.app.users
  CHANGES.rst
  Products/CMFPlone/skins/plone_login/registered.pt
  Products/CMFPlone/skins/plone_login/registered.pt.metadata
Labels: 04 type: enhancement, 23 status: testing

#2410 Add Plone Site: do a transaction commit before profiles
  CHANGES.rst
  Products/CMFPlone/factory.py
Labels: 01 type: bug, 13 prio: normal, 24 status: ready, 32 needs: review

#2413 After site creation, do not render a template: we redirect anyway [5.2]
  CHANGES.rst
  Products/CMFPlone/browser/admin.py
Labels: 01 type: bug, 13 prio: normal, 24 status: ready, 32 needs: review

#2414 After site creation, do not render a template: we redirect anyway [5.1]
  CHANGES.rst
  Products/CMFPlone/browser/admin.py
Labels: 01 type: bug, 13 prio: normal, 24 status: ready, 32 needs: review

#2416 Do not include too new upgrades when upgrading Plone Site. [5.2]
  CHANGES.rst
  Products/CMFPlone/MigrationTool.py
  Products/CMFPlone/browser/admin.py
  Products/CMFPlone/tests/testMigrationTool.py
Labels: 01 type: bug, 13 prio: normal, 23 status: testing

#2418 Do not include too new upgrades when upgrading Plone Site. [4.3]
  Products/CMFPlone/MigrationTool.py
  Products/CMFPlone/browser/admin.py
  Products/CMFPlone/tests/testMigrationTool.py
  docs/CHANGES.rst
Labels: 01 type: bug, 13 prio: normal, 23 status: testing

#2432 When allowing unicode ids in py3 Zope changes the regex for allowed i…
  CHANGES.rst
  Products/CMFPlone/tests/testCheckId.py
Labels: 24 status: ready
