Repository plone/Products.CMFPlone, pull requests merged in 2018-09, with the labels that each got.

#2503 Fixed combine-bundles step to work with keyword in registry directory.
  CHANGES.rst
  Products/CMFPlone/resources/exportimport/bundles.py
  Products/CMFPlone/tests/test_metabundles.py
Labels: 01 type: bug, 13 prio: normal, 24 status: ready, 32 needs: review

#1963 fix #1811: Remove last legacy Javascript highlight-searchterms.js
  CHANGES.rst
  Products/CMFPlone/profiles/default/skins.xml
  Products/CMFPlone/profiles/dependencies/registry.xml
  Products/CMFPlone/skins/plone_ecmascript/jquery.highlightsearchterms.js
  Products/CMFPlone/tests/testCSSandJSRegistry.py
Labels: 04 type: enhancement, 14 prio: low, 22 status: in-progress, 31 needs: help, 42 lvl: moderate

#2509 Backport remove highlightsearchterms
  CHANGES.rst
  Products/CMFPlone/profiles/default/skins.xml
  Products/CMFPlone/profiles/dependencies/registry.xml
  Products/CMFPlone/skins/plone_ecmascript/jquery.highlightsearchterms.js
  Products/CMFPlone/tests/testCSSandJSRegistry.py
Labels: 01 type: bug

#2444 Remove unused mail_password.py from skins/plone_scripts
  CHANGES.rst
  Products/CMFPlone/browser/login/configure.zcml
  Products/CMFPlone/browser/login/mail_password.py
  Products/CMFPlone/skins/plone_scripts/mail_password.py
Labels: 04 type: enhancement, 23 status: testing
