Repository plone/Products.CMFPlone, pull requests merged in 2018-12, with the labels that each got.

#2641 Meta bundle ordering [5.1]
  Products/CMFPlone/resources/browser/combine.py
  Products/CMFPlone/tests/test_metabundles.py
  news/2641.bugfix
Labels: 01 type: bug, 23 status: testing, 32 needs: review

#2630 Fix tinymce--missing fixes from 5.1/5.0
  Products/CMFPlone/_scripts/_generate_gruntfile.py
  Products/CMFPlone/profiles/dependencies/registry.xml
  news/2630.bugfix
Labels: 01 type: bug, 24 status: ready

#2648 Restore the possibility to sort catalog query results with multiple indexes [5.2.x]
  Products/CMFPlone/CatalogTool.py
  Products/CMFPlone/tests/testCatalogTool.py
  news/2464.fixed
Labels: 24 status: ready

#2647 Restore the possibility to sort catalog query results with multiple indexes [5.1.x]
  Products/CMFPlone/CatalogTool.py
  Products/CMFPlone/tests/testCatalogTool.py
  news/2464.fixed
Labels: 24 status: ready

#2644 Add async and defer attributes to bundles
  Products/CMFPlone/interfaces/resources.py
  Products/CMFPlone/profiles/dependencies/registry.xml
  Products/CMFPlone/resources/browser/scripts.pt
  Products/CMFPlone/resources/browser/scripts.py
  Products/CMFPlone/static/resourceregistry-compiled.css
  Products/CMFPlone/static/resourceregistry-compiled.css.map
  Products/CMFPlone/static/resourceregistry-compiled.js
  Products/CMFPlone/static/resourceregistry-compiled.min.js
  Products/CMFPlone/static/resourceregistry-compiled.min.js.map
  Products/CMFPlone/tests/testResourceRegistries.py
  news/2644.feature
Labels: 04 type: enhancement, 24 status: ready

#2649 Add async and defer attributes to bundles (5.2)
  Products/CMFPlone/interfaces/resources.py
  Products/CMFPlone/profiles/dependencies/registry.xml
  Products/CMFPlone/resources/browser/scripts.pt
  Products/CMFPlone/resources/browser/scripts.py
  Products/CMFPlone/tests/testResourceRegistries.py
  news/2649.feature
Labels: 04 type: enhancement, 22 status: in-progress

#2651 [5.0.x] Restore the possibility to sort catalog query results with multiple indexes
  Products/CMFPlone/CatalogTool.py
  Products/CMFPlone/tests/testCatalogTool.py
  news/2464.fixed
Labels: 24 status: ready

#2656 Do not load the production bundles with async or defer (Plone 5.1)
  Products/CMFPlone/resources/browser/scripts.py
  Products/CMFPlone/static/plone.js
  Products/CMFPlone/tests/testResourceRegistries.py
  news/2656.feature
Labels: 01 type: bug, 23 status: testing

#2657 Do not load the production bundles with async or defer (Plone 5.2)
  Products/CMFPlone/resources/browser/scripts.py
  Products/CMFPlone/static/plone.js
  Products/CMFPlone/tests/testResourceRegistries.py
  news/2649.feature
Labels: 01 type: bug, 23 status: testing

#2670 Fixes #2669 robot test test_edit_user_schema
  Products/CMFPlone/tests/robot/test_edit_user_schema.robot
  news/2669.bugfix
Labels: 01 type: bug, 11 prio: blocker, 23 status: testing

#2671 fixes #2669 on 5.1: Fix robot test test_edit_user_schema
  Products/CMFPlone/tests/robot/test_edit_user_schema.robot
  news/2669.bugfix
Labels: 01 type: bug, 11 prio: blocker, 23 status: testing

#2672 fixes #2669 on 5.1: Fix robot test test_edit_user_schema
  Products/CMFPlone/tests/robot/test_edit_user_schema.robot
  news/2669.bugfix
Labels: 01 type: bug, 13 prio: normal, 23 status: testing
