Repository plone/Products.CMFPlone, pull requests merged in 2018-11, with the labels that each got.

#2616 Replace slimit with calmjs.parse
  CHANGES.rst
  Products/CMFPlone/resources/browser/cook.py
  setup.py
Labels: 04 type: enhancement, 23 status: testing

#2632 Meta bundle ordering(5.0)
  Products/CMFPlone/resources/browser/combine.py
  Products/CMFPlone/tests/test_metabundles.py
  news/2632.bugfix
Labels: 01 type: bug, 23 status: testing, 32 needs: review

#2638 Delete fa_ir.js
  Products/CMFPlone/static/components/pickadate/lib/translations/fa_ir.js
  news/2620.bugfix
Labels: 01 type: bug, 13 prio: normal, 23 status: testing, 32 needs: review
