Repository plone/Products.CMFPlone, pull requests merged in 2018-10, with the labels that each got.

#2424 move test and init of gopipindex to Products.CMFPlone
  CHANGES.rst
  Products/CMFPlone/CatalogTool.py
  Products/CMFPlone/__init__.py
  Products/CMFPlone/configure.zcml
  Products/CMFPlone/factory.py
  Products/CMFPlone/tests/test_nogopip.py
  Products/CMFPlone/utils.py
  setup.py
Labels: 22 status: in-progress

#2550 Removed the raiseUnauthorized skin script.
  CHANGES.rst
  Products/CMFPlone/skins/plone_scripts/raiseUnauthorized.py
Labels: 01 type: bug, 13 prio: normal, 23 status: testing, 32 needs: review

#2567 Remove view history perm
  CHANGES.rst
  Products/CMFPlone/profiles/default/rolemap.xml
  Products/CMFPlone/tests/testSiteAdminRole.py
Labels: 23 status: testing

#2586 Revert "Fixed tests when IRichText behavior is used."
  CHANGES.rst
  Products/CMFPlone/tests/AddMoveAndDeleteDocument.txt
  Products/CMFPlone/tests/browser_collection_views.txt
Labels: 02 type: regression, 12 prio: high, 24 status: ready, 32 needs: review

#2584 Added utils.check_id function. [5.1]
  CHANGES.rst
  Products/CMFPlone/tests/testCheckId.py
  Products/CMFPlone/utils.py
Labels: 04 type: enhancement, 13 prio: normal, 23 status: testing, 32 needs: review

#2600 Removed generateUniqueId.py skins script
  CHANGES.rst
  Products/CMFPlone/skins/plone_scripts/generateUniqueId.py
  Products/CMFPlone/tests/testNavigationView.py
Labels: 04 type: enhancement
