Repository plone/Products.CMFPlone, pull requests merged in 2018-03, with the labels that each got.

#2328 Render exceptions as preformatted text
  CHANGES.rst
  Products/CMFPlone/browser/exceptions.py
  Products/CMFPlone/browser/templates/error_message.pt
Labels: 35 needs: rebase

#2239 Drops "type" from "script", "link" and "style" tags
  CHANGES.rst
  Products/CMFPlone/resources/browser/scripts.pt
  Products/CMFPlone/resources/browser/styles.pt
Labels: 22 status: in-progress, 32 needs: review

#2197 Improve compatibility with Python3
  CHANGES.rst
  Products/CMFPlone/_compat.py
  Products/CMFPlone/interfaces/controlpanel.py
Labels: 04 type: enhancement, 24 status: ready

#2324 Fix nested edit bar
  CHANGES.rst
  Products/CMFPlone/static/patterns/toolbar/src/toolbar.js
Labels: 01 type: bug, 24 status: ready, 32 needs: review

#2342 Advanced Catalog Clear And Rebuild
  CHANGES.rst
  Products/CMFPlone/CatalogTool.py
Labels: 01 type: bug, 04 type: enhancement, 22 status: in-progress

#2360 Fix to make plone/plone.session#11 work
  CHANGES.rst
  Products/CMFPlone/controlpanel/tests/test_controlpanel_installer.py
Labels: 04 type: enhancement, 23 status: testing

#2362 A not yet installed product must not return any upgrade info
  CHANGES.rst
  Products/CMFPlone/controlpanel/browser/quickinstaller.py
  Products/CMFPlone/controlpanel/tests/test_controlpanel_installer.py
Labels: 01 type: bug, 23 status: testing

#2367 Fixed bug in ajax standard_error_message.
  CHANGES.rst
  Products/CMFPlone/skins/plone_templates/standard_error_message.py
Labels: 01 type: bug, 24 status: ready, 32 needs: review
