Repository plone/Products.CMFPlone, pull requests merged in 2018-08, with the labels that each got.

#2479 Add X-Content-Type-Options and X-XSS-Protection security headers
  Products/CMFPlone/skins/plone_templates/main_template.pt
  docs/CHANGES.rst
Labels: 04 type: enhancement, 13 prio: normal, 24 status: ready, 32 needs: review, 41 lvl: easy

#2484 Get rid of obsolete X-UA-Compatible header
  CHANGES.rst
  Products/CMFPlone/static/components/ace-builds/editor.html
  Products/CMFPlone/static/components/backbone/index.html
Labels: 04 type: enhancement, 13 prio: normal, 24 status: ready, 32 needs: review, 41 lvl: easy, 99 tag: cleanup

#2498 Fix registration of robots.txt browser view to avoid AttributeError on Zope's root
  CHANGES.rst
  Products/CMFPlone/browser/configure.zcml
Labels: 13 prio: normal, 24 status: ready, 32 needs: review

#2497 Fix registration of robots.txt browser view to avoid AttributeError on Zope's root
  CHANGES.rst
  Products/CMFPlone/browser/configure.zcml
Labels: 24 status: ready, 32 needs: review, 41 lvl: easy

#2483 Get rid of obsolete X-UA-Compatible header
  CHANGES.rst
  Products/CMFPlone/static/components/ace-builds/editor.html
  Products/CMFPlone/static/components/backbone/index.html
Labels: 04 type: enhancement, 13 prio: normal, 24 status: ready, 32 needs: review, 41 lvl: easy, 99 tag: cleanup

#2496 Fix registration of robots.txt browser view to avoid AttributeError on Zope's root
  CHANGES.rst
  Products/CMFPlone/browser/configure.zcml
Labels: 24 status: ready, 32 needs: review, 41 lvl: easy

#2495 Move leftovers from controlpanel over here
  CHANGES.rst
  Products/CMFPlone/configure.zcml
  Products/CMFPlone/controlpanel/configure.zcml
  Products/CMFPlone/controlpanel/permissions.zcml
  Products/CMFPlone/interfaces/controlpanel.py
  setup.py
Labels: 04 type: enhancement, 23 status: testing
