Repository plone/Products.CMFPlone, pull requests merged in 2019-01, with the labels that each got.

#2675 [a11y] Added role attribute for portalMessage (5.1.x)
  CHANGES.rst
  Products/CMFPlone/browser/templates/author.pt
  Products/CMFPlone/controlpanel/browser/maintenance.pt
  Products/CMFPlone/controlpanel/browser/overview.pt
  Products/CMFPlone/controlpanel/browser/quickinstaller.pt
  Products/CMFPlone/controlpanel/browser/resourceregistry.pt
  Products/CMFPlone/controlpanel/browser/types.pt
  Products/CMFPlone/controlpanel/browser/usergroups_usersoverview.pt
  Products/CMFPlone/skins/plone_login/failsafe_login_form.cpt
  Products/CMFPlone/skins/plone_login/login_form.cpt
  Products/CMFPlone/skins/plone_prefs/prefs_error_log_showEntry.pt
  Products/CMFPlone/skins/plone_templates/test_rendering.pt
  news/2675.bugfix
Labels: 99 tag: UX Accessibility

#2695 fixed Python 3 related str decoding issue in breadcrumbs
  Products/CMFPlone/browser/search.py
  news/2694.fixed
Labels: 24 status: ready

#2708 Fixed unstable robot test Scenario: A page is opened to edit in TinyMCE.
  Products/CMFPlone/tests/robot/test_tinymce.robot
  news/2707.bugfix
Labels: 01 type: bug, 13 prio: normal, 23 status: testing, 32 needs: review
