Repository plone/Products.CMFPlone, pull requests merged in 2019-04, with the labels that each got.

#2826 Fixed unstable Markup Control Panel robot test again.
  Products/CMFPlone/tests/robot/test_controlpanel_markup.robot
  news/2809.bugfix
Labels: 02 type: regression, 13 prio: normal, 24 status: ready, 32 needs: review

#2801 Implement redirections features: store date and manual, export, bulk remove
  Products/CMFPlone/controlpanel/browser/redirects-controlpanel.pt
  Products/CMFPlone/controlpanel/browser/redirects-manage.pt
  Products/CMFPlone/controlpanel/browser/redirects.py
  Products/CMFPlone/controlpanel/tests/test_controlpanel_browser_redirection.py
  Products/CMFPlone/tests/robot/test_controlpanel_redirection.robot
  news/2799.feature.1
  news/2799.feature.2
  news/2799.feature.3
Labels: 04 type: enhancement, 13 prio: normal, 24 status: ready, 32 needs: review

#2827 fix encoding bug while cooking resources
  Products/CMFPlone/resources/browser/cook.py
  Products/CMFPlone/tests/testResourceRegistries.py
  news/2827.bugfix
Labels: 01 type: bug, 23 status: testing

#2831 Fix DeprecationWarning in syndication-view.
  Products/CMFPlone/browser/syndication/views.py
  news/2831.bugfix
Labels: 01 type: bug, 14 prio: low, 23 status: testing

#2843 Fix #2842: malformed url when redirecting to external login
  Products/CMFPlone/browser/login/login.py
  Products/CMFPlone/tests/test_login_form.py
  news/2842.bugfix
Labels: 01 type: bug
