Repository plone/Products.CMFPlone, pull requests merged in 2019-02, with the labels that each got.

#2714 Update the patch for zope.sendmail.mailer.SMTPMailer.__init__
  Products/CMFPlone/patches/sendmail.py
  news/2665.bugfix
Labels: 24 status: ready

#2622 Plip 2516 navigation
  Products/CMFPlone/interfaces/controlpanel.py
  Products/CMFPlone/profiles/default/catalog.xml
  Products/CMFPlone/profiles/default/metadata.xml
  Products/CMFPlone/profiles/dependencies/registry.xml
  Products/CMFPlone/static/plone-compiled.css
  Products/CMFPlone/static/plone-compiled.css.map
  Products/CMFPlone/static/plone-compiled.js
  Products/CMFPlone/static/plone-compiled.min.js
  Products/CMFPlone/static/plone-compiled.min.js.map
  Products/CMFPlone/static/plone.js
  news/2516.feature
Labels: 03 type: feature (plip), 24 status: ready

#2739 Do not mark special links by default
  Products/CMFPlone/interfaces/controlpanel.py
  news/2736.feature
Labels: 24 status: ready

#2256 WIP: Add redirection control panel
  Products/CMFPlone/controlpanel/browser/configure.zcml
  Products/CMFPlone/controlpanel/browser/redirects-controlpanel.pt
  Products/CMFPlone/controlpanel/browser/redirects-manage.pt
  Products/CMFPlone/controlpanel/browser/redirects.py
  Products/CMFPlone/controlpanel/tests/test_controlpanel_browser_redirection.py
  Products/CMFPlone/profiles/default/actions.xml
  Products/CMFPlone/profiles/default/controlpanel.xml
  Products/CMFPlone/profiles/default/rolemap.xml
  Products/CMFPlone/tests/testPortalCreation.py
  news/1486.feature
Labels: 04 type: enhancement, 22 status: in-progress, 35 needs: rebase

#2743 Fix excluded items in navigation
  Products/CMFPlone/browser/navigation.py
  Products/CMFPlone/tests/testNavigationView.py
  news/2516.fixed
Labels: 24 status: ready

#2770 Display wsgi-status and name/version of used server
  Products/CMFPlone/controlpanel/browser/overview.pt
  Products/CMFPlone/controlpanel/browser/overview.py
  news/2770.feature
Labels: 04 type: enhancement, 22 status: in-progress
