Repository plone/Products.CMFPlone, pull requests merged in 2019-03, with the labels that each got.

#2778 Mail controlpanel permission
  Products/CMFPlone/controlpanel/browser/configure.zcml
  news/2688.bugfix
Labels: 01 type: bug

#2715 Add basic validators for the portal action controlpanel forms
  Products/CMFPlone/interfaces/controlpanel.py
  news/2689.bugfix
Labels: 24 status: ready

#2810 Fix several unstable robot tests
  Products/CMFPlone/tests/robot/test_controlpanel_markup.robot
  Products/CMFPlone/tests/robot/test_querystring.robot
  news/2808.bugfix
  news/2809.bugfix
Labels: 01 type: bug, 13 prio: normal, 23 status: testing, 32 needs: review

#2811 Fix some more unstable robot tests by adding waits
  Products/CMFPlone/tests/robot/test_actionmenu.robot
  Products/CMFPlone/tests/robot/test_controlpanel_actions.robot
  Products/CMFPlone/tests/robot/test_controlpanel_editing.robot
  Products/CMFPlone/tests/robot/test_controlpanel_filter.robot
  Products/CMFPlone/tests/robot/test_controlpanel_language.robot
  Products/CMFPlone/tests/robot/test_controlpanel_markup.robot
  Products/CMFPlone/tests/robot/test_controlpanel_navigation.robot
  Products/CMFPlone/tests/robot/test_controlpanel_search.robot
  Products/CMFPlone/tests/robot/test_controlpanel_security.robot
  Products/CMFPlone/tests/robot/test_controlpanel_site.robot
  Products/CMFPlone/tests/robot/test_controlpanel_social.robot
  Products/CMFPlone/tests/robot/test_controlpanel_types.robot
  Products/CMFPlone/tests/robot/test_controlpanel_usergroups.robot
  Products/CMFPlone/tests/robot/test_edit.robot
  Products/CMFPlone/tests/robot/test_edit_user_schema.robot
  Products/CMFPlone/tests/robot/test_linkintegrity.robot
  Products/CMFPlone/tests/robot/test_overlays.robot
  Products/CMFPlone/tests/robot/test_portlets.robot
  Products/CMFPlone/tests/robot/test_thememapper.robot
  Products/CMFPlone/tests/robot/test_tinymce.robot
  news/2809.bugfix
Labels: 01 type: bug, 13 prio: normal, 23 status: testing, 32 needs: review
