Repository plone/Products.CMFPlone, pull requests merged in 2019-12, with the labels that each got.

#2972 Removed broken X-XSS-Protection header.
  Products/CMFPlone/skins/plone_templates/main_template.pt
  Products/CMFPlone/testing.py
  Products/CMFPlone/tests/robot/test_classic.robot
  Products/CMFPlone/tests/robot/test_unstyled.robot
  Products/CMFPlone/tests/test_robot.py
  news/2964.bugfix
Labels: 02 type: regression, 12 prio: high, 24 status: ready, 32 needs: review

#2994 Correctly fire events when user auto login after the password has been reset
  Products/CMFPlone/browser/login/password_reset.py
  Products/CMFPlone/tests/pwreset_browser.rst
  news/2993.bugfix
Labels: 01 type: bug, 32 needs: review

#2915 Fix #2914: Fix the TinyMCE pattern loading HTML as CSS...
  Products/CMFPlone/patterns/tinymce.py
  news/2914.bugfix
Labels: 04 type: enhancement, 13 prio: normal, 24 status: ready
