Repository plone/Products.CMFPlone, pull requests merged in 2019-05, with the labels that each got.

#2855 Always add data-default-sort attribute to search results. [5.1]
  Products/CMFPlone/browser/search.py
  Products/CMFPlone/browser/templates/search.pt
  Products/CMFPlone/tests/testSearch.py
  news/2854.bugfix
Labels: 01 type: bug, 14 prio: low, 23 status: testing, 32 needs: review

#2856 Always add data-default-sort attribute to search results. [5.2]
  Products/CMFPlone/browser/search.py
  Products/CMFPlone/browser/templates/search.pt
  Products/CMFPlone/tests/testSearch.py
  news/2854.bugfix
Labels: 01 type: bug, 14 prio: low, 23 status: testing, 32 needs: review

#2858 remove verifydb, it was factored out to module zodbverify
  Products/CMFPlone/_scripts/__init__.py
  Products/CMFPlone/_scripts/verifydb.py
  news/2858.feature
  setup.py
Labels: 04 type: enhancement, 13 prio: normal, 23 status: testing

#2862 fix a bunch of deprecation warnings
  Products/CMFPlone/URLTool.py
  Products/CMFPlone/controlpanel/tests/test_controlpanel_browser_redirection.py
  Products/CMFPlone/factory.py
  Products/CMFPlone/resources/exportimport/resourceregistry.py
  Products/CMFPlone/tests/testBatch.py
  Products/CMFPlone/tests/testPortalCreation.py
  news/2862.bugfix
Labels: 04 type: enhancement, 14 prio: low, 23 status: testing

#2871 Fix scripts.pt Parsing Errors & Self-Closing Tags
  Products/CMFPlone/resources/browser/scripts.pt
  news/2870.bugfix
Labels: 01 type: bug, 14 prio: low, 23 status: testing
