Repository plone/Products.CMFPlone, pull requests merged in 2020-06, with the labels that each got.

#3116 Fixed saving ignored exception types in Python 3.
  Products/CMFPlone/skins/plone_prefs/prefs_error_log_setProperties.py
  news/3115.bugfix
Labels: 02 type: regression, 13 prio: normal, 24 status: ready, 32 needs: review

#3117 Add custom.css resource after diazo bundle [5.2]
  Products/CMFPlone/resources/browser/styles.py
  news/3086.feature
Labels: 04 type: enhancement, 13 prio: normal, 23 status: testing, 32 needs: review

#3118 Only add custom.css bundle when it is set in the theming control panel [5.2]
  Products/CMFPlone/resources/browser/styles.py
  news/3086.feature
Labels: 04 type: enhancement, 13 prio: normal, 23 status: testing, 32 needs: review

#3097 Catch more errors in generating scripts listing when bundle resources…
  Products/CMFPlone/resources/browser/combine.py
  Products/CMFPlone/resources/bundle.py
  Products/CMFPlone/tests/testResourceRegistries.py
  news/3096.bugfix
Labels: 01 type: bug, 22 status: in-progress, 31 needs: help

#3101 Backport #2860 for Plone 5.2
  Products/CMFPlone/patterns/tinymce.py
  news/2861.bugfix
Labels: 24 status: ready
