Repository plone/Products.CMFPlone, pull requests merged in 2020-04, with the labels that each got.

#3077 Add markdown extension settings to markup control panel.
  Products/CMFPlone/controlpanel/tests/test_controlpanel_browser_markup.py
  Products/CMFPlone/controlpanel/tests/test_controlpanel_markup.py
  Products/CMFPlone/interfaces/controlpanel.py
  news/3076.feature
Labels: 04 type: enhancement, 13 prio: normal, 22 status: in-progress

#3082 Fix py38 time.clock removal
  Products/CMFPlone/CatalogTool.py
  news/3082.bugfix
Labels: 01 type: bug, 23 status: testing

#3084 enable custom format string i18n/l10n
  Products/CMFPlone/i18nl10n.py
  Products/CMFPlone/tests/test_doctests.py
  Products/CMFPlone/tests/test_l18nl10n.py
  news/3084.feature
Labels: 04 type: enhancement, 14 prio: low, 23 status: testing

#3015 Fix redirect issues
  Products/CMFPlone/browser/exceptions.py
  Products/CMFPlone/browser/templates/error_message.pt
  Products/CMFPlone/tests/test_error_message.py
  news/3014.bugfix
Labels: 22 status: in-progress, 24 status: ready
