Repository plone/Products.CMFPlone, pull requests merged in 2020-02, with the labels that each got.

#3041 make setup.py reflect to be Plone 6 and Py3 only
  news/3041.breaking
  setup.py
Labels: 04 type: enhancement, 24 status: ready

#3038 [6.0] Improve tests for the workflow tool method listWFStatesByTitle
  Products/CMFPlone/tests/testWorkflowTool.py
  news/3032.bugfix
Labels: 24 status: ready

#3036 [5.2] Improve tests for the workflow tool method listWFStatesByTitle
  Products/CMFPlone/tests/testWorkflowTool.py
  news/3032.bugfix
Labels: 24 status: ready

#3037 [5.1] Improve tests for the workflow tool method listWFStatesByTitle
  Products/CMFPlone/tests/testWorkflowTool.py
  news/3032.bugfix
Labels: 24 status: ready

#2887 Allow ``figcaption`` in rich text editor as a valid tag.
  Products/CMFPlone/interfaces/controlpanel.py
  news/2887.feature
Labels: 04 type: enhancement, 24 status: ready

#3045 Merge PloneHotfix20200121 isURLInPortal and password strength [master]
  Products/CMFPlone/RegistrationTool.py
  Products/CMFPlone/URLTool.py
  Products/CMFPlone/tests/testRegistrationTool.py
  Products/CMFPlone/tests/testURLTool.py
  news/3021.bugfix.1
  news/3021.bugfix.2
Labels: 01 type: bug, 11 prio: blocker, 23 status: testing, 32 needs: review

#3054 Fixed TypeError when adding both a group and a user to a group. [5.2]
  Products/CMFPlone/controlpanel/browser/usergroups_groupmembership.py
  Products/CMFPlone/controlpanel/tests/test_controlpanel_browser_usergroups.py
  news/3084.bugfix
Labels: 02 type: regression, 13 prio: normal, 23 status: testing, 32 needs: review

#3043 Merge PloneHotfix20200121 isURLInPortal and password strength [5.1]
  Products/CMFPlone/RegistrationTool.py
  Products/CMFPlone/URLTool.py
  Products/CMFPlone/tests/testControlPanelScripts.py
  Products/CMFPlone/tests/testRegistrationTool.py
  Products/CMFPlone/tests/testURLTool.py
  news/3021.bugfix.1
  news/3021.bugfix.2
Labels: 01 type: bug, 11 prio: blocker, 23 status: testing, 32 needs: review

#3044 Merge PloneHotfix20200121 isURLInPortal and password strength [5.2]
  Products/CMFPlone/RegistrationTool.py
  Products/CMFPlone/URLTool.py
  Products/CMFPlone/tests/testRegistrationTool.py
  Products/CMFPlone/tests/testURLTool.py
  news/3021.bugfix.1
  news/3021.bugfix.2
Labels: 01 type: bug, 11 prio: blocker, 23 status: testing, 32 needs: review

#3060 fixes #3059 ReplaceableWrapper does not work
  Products/CMFPlone/PloneFolder.py
  Products/CMFPlone/Portal.py
  news/3060.bugfix
  setup.cfg
Labels: 01 type: bug, 14 prio: low, 23 status: testing
