Repository plone/Products.CMFPlone, pull requests merged in 2021-11, with the labels that each got.

#3344 On Zope root, create Volto site by default.
  Products/CMFPlone/browser/admin.py
  Products/CMFPlone/browser/templates/plone-overview.pt
  news/3344.feature
Labels: 04 type: enhancement, 32 needs: review, 24 status: ready, 12 prio: high

#3316 [5.2] The portal catalog will not try to index itself anymore
  Products/CMFPlone/CatalogTool.py
  news/3312.bugfix
Labels: 23 status: testing, 24 status: ready

#3357 fixes #3352 - p.a.iterate dependency indirection
  Products/CMFPlone/relationhelper.py
  news/3357.bugfix
Labels: 23 status: testing, 01 type: bug, 12 prio: high

#3362 Fix random failure in test_querystring.robot
  Products/CMFPlone/tests/robot/test_querystring.robot
Labels: 24 status: ready

#3361 Remove adapter for index location
  Products/CMFPlone/CatalogTool.py
  Products/CMFPlone/catalog.zcml
  news/3347.bugfix
Labels: 24 status: ready

#3364 Fix random fails in test_querystring.robot
  Products/CMFPlone/tests/robot/test_querystring.robot
Labels: 01 type: bug, 24 status: ready

#3366 Cleanup Portal
  Products/CMFPlone/Portal.py
  news/3337.bugfix
  news/3366.bugfix
Labels: 23 status: testing, 04 type: enhancement, 14 prio: low

#3367 fix #3323
  Products/CMFPlone/Portal.py
  news/3323.bugifx
Labels: 23 status: testing, 01 type: bug, 12 prio: high
