Repository plone/Products.CMFPlone, pull requests merged in 2021-09, with the labels that each got.

#2612 PLIP 2454 DX Plone Site
  Products/CMFPlone/Portal.py
  Products/CMFPlone/browser/admin.py
  Products/CMFPlone/configure.zcml
  Products/CMFPlone/factory.py
  Products/CMFPlone/profiles/default/types.xml
  Products/CMFPlone/profiles/default/types/Plone_Site.xml
  Products/CMFPlone/skins/plone_templates/index_html.pt
  Products/CMFPlone/skins/plone_templates/index_html.pt.metadata
  Products/CMFPlone/tests/testActionsTool.py
  Products/CMFPlone/tests/testCatalogTool.py
  Products/CMFPlone/tests/testPloneFolder.py
  Products/CMFPlone/tests/testPortalCreation.py
  Products/CMFPlone/tests/testWebDAV.py
  Products/CMFPlone/tests/test_safe_formatter.py
  news/2454.breaking
Labels: 22 status: in-progress, 35 needs: rebase, 03 type: feature (plip)

#3311 Add plone.app.caching to list of add-ons to upgrade
  Products/CMFPlone/MigrationTool.py
  news/82.bugfix
Labels: 23 status: testing, 04 type: enhancement, 32 needs: review, 12 prio: high

#3315 The portal catalog will not try to index itself anymore
  Products/CMFPlone/CatalogTool.py
  news/3312.bugfix
Labels: 23 status: testing, 01 type: bug

#3317 Fixed DeprecationWarning for ComponentLookupError.
  Products/CMFPlone/Portal.py
Labels: 23 status: testing, 01 type: bug, 32 needs: review, 13 prio: normal
