Repository plone/Products.CMFPlone, pull requests merged in 2021-01, with the labels that each got.

#3193 Removed content_status_modify.cpy script and its validator [Plone 6]
  Products/CMFPlone/skins/plone_form_scripts/content_status_modify.cpy
  Products/CMFPlone/skins/plone_form_scripts/content_status_modify.cpy.metadata
  Products/CMFPlone/skins/plone_form_scripts/validate_content_status_modify.vpy
  Products/CMFPlone/tests/testContentPublishing.py
  Products/CMFPlone/tests/testContentSecurity.py
  news/3057.breaking.1
  news/3057.breaking.2
Labels: 04 type: enhancement, 13 prio: normal, 24 status: ready, 32 needs: review

#3228 Removed dependency on ``Products.TemporaryFolder``.
  news/2957.breaking
  setup.py
Labels: 04 type: enhancement, 13 prio: normal, 23 status: testing, 32 needs: review

#3230 Plone 6: Removed dependency on Products.Sessions.
  news/2957.bugfix
  setup.py
Labels: 04 type: enhancement, 13 prio: normal, 24 status: ready, 32 needs: review

#3224 Fix problem to remove username and password if there was already one set
  Products/CMFPlone/controlpanel/browser/mail.py
  news/3224.bugfix
Labels: 01 type: bug, 13 prio: normal, 23 status: testing
