Repository plone/Products.CMFPlone, pull requests merged in 2021-12, with the labels that each got.

#3340 PLIP 3339: Replace z3c.autoinclude with plone.autoinclude.
  Products/CMFPlone/configure.zcml
  Products/CMFPlone/meta.zcml
  Products/CMFPlone/overrides.zcml
  news/3339.breaking
  setup.py
Labels: 23 status: testing, 32 needs: review, 03 type: feature (plip), 13 prio: normal

#3376 Enable warnings TTW (like a DeprecationWarning)
  Products/CMFPlone/__init__.py
  news/3376.feature
Labels: 23 status: testing, 04 type: enhancement, 13 prio: normal

#3377 Optional hook to customize breadcrumbs like navigation
  Products/CMFPlone/browser/navigation.py
  news/3377.feature
Labels: 04 type: enhancement, 22 status: in-progress, 13 prio: normal

#3385 Removed management_page_charset support from usergroup-groupdetails
  Products/CMFPlone/controlpanel/browser/usergroups_groupdetails.pt
  news/3305.bugfix
Labels: 04 type: enhancement, 32 needs: review, 24 status: ready, 13 prio: normal
