Repository plone/Products.CMFPlone, pull requests merged in 2022-09, with the labels that each got.

#3640 Admin UI tweaks
  Products/CMFPlone/browser/static/plone-admin-ui.css
  Products/CMFPlone/browser/templates/plone-overview.pt
  Products/CMFPlone/browser/templates/plone-upgrade.pt
  news/3640.bugfix
Labels: 23 status: testing, 04 type: enhancement, 14 prio: low

#3642 Fix aliased helpers
  Products/CMFPlone/utils.py
  news/3641.bugfix
Labels: 23 status: testing

#3646 Make tests pass with longer minimum password
  Products/CMFPlone/controlpanel/tests/test_controlpanel_browser_maintenance.py
  Products/CMFPlone/controlpanel/tests/test_controlpanel_browser_usergroups_siteadmin_role.py
  Products/CMFPlone/testing.py
  Products/CMFPlone/tests/LoginAndLogout.rst
  Products/CMFPlone/tests/csrf.txt
  Products/CMFPlone/tests/pwreset_browser.rst
  Products/CMFPlone/tests/robot/test_overlays.robot
  Products/CMFPlone/tests/search_form.rst
  Products/CMFPlone/tests/testActionsTool.py
  Products/CMFPlone/tests/testCSRFProtection.py
  Products/CMFPlone/tests/testCatalogTool.py
  Products/CMFPlone/tests/testContentSecurity.py
  Products/CMFPlone/tests/testCutPasteSecurity.py
  Products/CMFPlone/tests/testEmailLogin.py
  Products/CMFPlone/tests/testExternalEditorEnabled.py
  Products/CMFPlone/tests/testPloneTool.py
  Products/CMFPlone/tests/testRegistrationTool.py
  Products/CMFPlone/tests/testWorkflowTool.py
  Products/CMFPlone/tests/test_login_form.py
  Products/CMFPlone/tests/test_login_logout.py
  news/3646.bugfix
Labels: 24 status: ready

#3645 Deprecate the portal_properties tool
  Products/CMFPlone/PropertiesTool.py
  news/125.bugfix
Labels: 24 status: ready
