Repository plone/Products.CMFPlone, pull requests merged in 2022-08, with the labels that each got.

#3610 Supress warning of intentional deprecated import for BBB.
  Products/CMFPlone/__init__.py
  news/3610.bugfix
Labels: 23 status: testing, 14 prio: low

#3616 Fix actions
  Products/CMFPlone/ActionsTool.py
  Products/CMFPlone/PloneBaseTool.py
  Products/CMFPlone/profiles/default/actions.xml
  Products/CMFPlone/tests/testPortalCreation.py
  news/3616.bugfix
Labels: 23 status: testing, 04 type: enhancement

#3630 [5.2] Add the timezone property to the member properties
  Products/CMFPlone/profiles/default/memberdata_properties.xml
  news/1290.bugfix
Labels: 24 status: ready
