Repository plone/Products.CMFPlone, pull requests merged in 2024-05, with the labels that each got.

#3945 Remove Deprecation: import INavigationRoot from plone.base
  Products/CMFPlone/browser/admin.zcml
  Products/CMFPlone/browser/configure.zcml
  Products/CMFPlone/browser/login/configure.zcml
  news/3945.bugfix
Labels: 23 status: testing, 01 type: bug, 14 prio: low

#3946 use context instead of here and prefix main_template with @@
  Products/CMFPlone/browser/login/templates/explainPWResetTool.pt
  Products/CMFPlone/browser/login/templates/login.pt
  Products/CMFPlone/browser/login/templates/login_help.pt
  Products/CMFPlone/controlpanel/browser/redirects-manage.pt
  news/3946.bugfix
Labels: 23 status: testing, 01 type: bug, 14 prio: low

#3960 Remove queryCatalog and getFolderContents skin scripts
  Products/CMFPlone/browser/syndication/adapters.py
  Products/CMFPlone/browser/syndication/templates/search-rss.pt
  Products/CMFPlone/browser/syndication/views.py
  Products/CMFPlone/skins/plone_scripts/getFolderContents.py
  Products/CMFPlone/skins/plone_scripts/queryCatalog.py
  Products/CMFPlone/tests/testNavTree.py
  Products/CMFPlone/tests/testQueryCatalog.py
  Products/CMFPlone/tests/testSecurity.py
  news/3960.bugfix
Labels: 23 status: testing, 04 type: enhancement, 14 prio: low

#3949 Reduce deprecation warnings.
  Products/CMFPlone/browser/navigation.py
  Products/CMFPlone/browser/navtree.py
  Products/CMFPlone/browser/search.py
  Products/CMFPlone/controlpanel/tests/test_controlpanel_browser_redirection.py
  Products/CMFPlone/tests/testNavTree.py
  Products/CMFPlone/tests/testSecurityDeclarations.py
  news/3949.bugfix
Labels: 23 status: testing, 01 type: bug, 14 prio: low

#3963 fixes #3962
  Products/CMFPlone/controlpanel/browser/error_log_form.py
  news/3962.bugfix
  setup.py
Labels: 23 status: testing, 01 type: bug, 11 prio: blocker

#3967 Hide shutdown if not possible.
  Products/CMFPlone/controlpanel/browser/maintenance.pt
  Products/CMFPlone/controlpanel/browser/maintenance.py
  Products/CMFPlone/controlpanel/tests/test_controlpanel_browser_maintenance.py
  Products/CMFPlone/tests/csrf.txt
  news/3967.bugfix
Labels: 01 type: bug

#3964 Fix duplicate "content" id in controlpanels
  Products/CMFPlone/controlpanel/browser/usergroups_groupdetails.pt
  Products/CMFPlone/controlpanel/browser/usergroups_groupmembership.pt
  Products/CMFPlone/controlpanel/browser/usergroups_groupsoverview.pt
  Products/CMFPlone/controlpanel/browser/usergroups_usermembership.pt
  Products/CMFPlone/controlpanel/browser/usergroups_usersoverview.pt
  news/3964.bugfix
Labels: 23 status: testing, 01 type: bug, 14 prio: low
